# Generated by Django 3.0.8 on 2020-07-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='class_id',
            new_name='clas',
        ),
    ]
