# Generated by Django 3.0.8 on 2020-07-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20200718_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='clas',
            new_name='class_room',
        ),
        migrations.RenameField(
            model_name='internal',
            old_name='clas',
            new_name='class_room',
        ),
    ]
