# Generated by Django 3.0.8 on 2020-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
