# Generated by Django 3.0.8 on 2020-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypoint', '0002_activitypoints_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypoints',
            name='activity',
            field=models.CharField(choices=[('ncc', 'N C C'), ('nss', 'N S S'), ('sports', 'Sports'), ('games', 'Games'), ('music', 'Music'), ('performingarts', 'Performing Arts'), ('literaryarts', 'Literary arts'), ('techfestquiz', 'Tech Fest, Tech Quiz'), ('moocfinalass', 'Massive Open Online Courses with final assessment certificate'), ('competition', 'Competition conducted by Professional Societies - (IEEE, IET, ASME, SAE, NASA etc.)'), ('attendingseminariit', 'Attending Full time Conference/Seminars/Exhibitions/Workshop/ STTP conducted at IITs /NITs'), ('attendingseminarktu', 'Attending Full time Conference/Seminars/Exhibitions/Workshop/ STTP conducted at KTU or its affiliated institutes'), ('paperiit', 'Paper presentation/publication at IITs/NITs'), ('paperktu', 'Paper presentation/publication at KTU or its affiliated institutes'), ('posteriit', 'Poster Presentation at IITs /NITs'), ('posterktu', 'Poster Presentation at KTU or its affiliated institutes'), ('industrialtraining', 'Industrial Training/Internship (atleast for 5 full days)'), ('industrialexhibition', 'Industrial/Exhibition visits'), ('foreign', 'Foreign Language Skill(TOEFL/IELTS/ BEC examsetc.)'), ('startup', 'Start-up Company –Registered legally'), ('pfield', 'Patent - Filed'), ('ppublished', 'Patent - Published'), ('papproved', 'Patent- Approved'), ('plicensed', 'Patent- Licensed'), ('prototype', 'Prototype developed and tested'), ('awards', 'Awards for Products developed'), ('innovative', 'Innovative technologies developed and used by industries/users'), ('gotventure', 'Got Venture capital funding for innovative ideas/products'), ('startup', 'Startup Employment(Offering jobs to two persons not less than Rs. 15000/- per month)'), ('societal', 'Societal innovations'), ('studentps', 'Student Professional Societies (IEEE, IET, ASME, SAE, NASA etc.)'), ('college', 'College Association Chapters(Mechanical, Civil, Electrical etc.)'), ('festival', 'Festival & Technical Events(College approved)'), ('hobbyclub', 'Hobby Club'), ('elected', 'Elected student representatives')], default='ncc', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitypoints',
            name='activitylevel',
            field=models.CharField(choices=[('notapplicable', 'Not Applicable'), ('collegeevents', 'I (College Events)'), ('zonalevents', 'II (Zonal Events)'), ('stateuniversityevents', 'III (State/ University Events)'), ('nationalevents', 'IV (National Events)'), ('internationalevents', 'V (International Events)')], default='notapplicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitypoints',
            name='involvement',
            field=models.CharField(choices=[('notapplicable', 'Not Applicable'), ('corecoordinator', 'Core coordinator'), ('subcoordinator', 'Sub coordinator'), ('volunteer', 'Volunteer')], default='notapplicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitypoints',
            name='prize',
            field=models.CharField(choices=[('notapplicable', 'Not Applicable'), ('participant', 'Participant'), ('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='notapplicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitypoints',
            name='year',
            field=models.CharField(choices=[('firstyear', 'First Year'), ('secondyear', 'Second Year'), ('thirdyear', 'Third Year'), ('fourthyear', 'Fourth Year')], default='firstyear', max_length=100),
        ),
    ]
